#! /usr/bin/env Rscript

library(MASS)
library(ggplot2)

args = commandArgs(trailingOnly=TRUE) # What you need to pass in arguements

#### Subroutines ####
fit_distributions <- function(tad_df, loop_df, back_df) {
  print("Start")
  tad_df <- na.omit(tad_df)
  loop_df <- na.omit(loop_df)
  back_df <- na.omit(back_df)
  
  dist_vals <- 99
  dist_matrix <- c()
  print("Looping")
  for( i in 0:dist_vals) {
    t <- as.integer(tad_df$reads[tad_df$distance == i])
    lf <- as.integer(loop_df$reads[loop_df$distance == i])
    b <- as.integer(back_df$reads[back_df$distance == i])

     #fit the distributions
    nbin_t <- fitdistr(as.integer(t), "negative binomial")
    gam_t <- fitdistr(as.integer(t), "gamma")
    print("t-done")
    nbin_lf <- fitdistr(as.integer(lf), "negative binomial")
    gam_lf <- fitdistr(as.integer(lf), "gamma")
    print("lf_done")
    
    b <- b+1
    nbin_b <- fitdistr(as.integer(b), "negative binomial")
    print("b-bin")
    gam_b <- fitdistr(as.integer(b), "gamma")
    print("b-gam")
    #Create data frame from the distributions generated
    
    #For all three at once
    dist_matrix <- append(dist_matrix, c(i,"TADs",nbin_t$estimate[1], nbin_t$estimate[2], gam_t$estimate[1], gam_t$estimate[2],
                                         i, "Loop&FL", nbin_lf$estimate[1], nbin_lf$estimate[2], gam_lf$estimate[1], gam_lf$estimate[2],
                                         i, "Background", nbin_b$estimate[1], nbin_b$estimate[2], gam_b$estimate[1], gam_b$estimate[2]) )
    print(i)
    #for a single one at a time
    #dist_matrix <- append(dist_matrix, c(i, "Loop&FL", nbin_lf$estimate[1], nbin_lf$estimate[2], gam_lf$estimate[1], gam_lf$estimate[2]))
  }
  
  #create a matrix from the vector
  dist_matrix <- matrix(dist_matrix, ncol = 6, byrow = TRUE)
  colnames(dist_matrix) <- c("distance", "model", "theta", "mu", "scale", "rate")
  
  #correct variable problems
  dist_matrix <- as.data.frame(dist_matrix)
  dist_matrix$distance <- as.integer(as.character(dist_matrix$distance))
  dist_matrix$model <- as.character(dist_matrix$model)
  dist_matrix$theta <- as.numeric(as.character(dist_matrix$theta))
  dist_matrix$mu <- as.numeric(as.character(dist_matrix$mu))
  dist_matrix$scale <- as.numeric(as.character(dist_matrix$scale))
  dist_matrix$rate <- as.numeric(as.character(dist_matrix$rate))
  
  return(as.data.frame(dist_matrix))
}

print_out_data <- function(name, dataframe, o) {
  write.table(dataframe, file = gsub(" ","",paste(o, "/", name, ".txt",sep = ""),fixed = TRUE), sep = "\t", row.names = FALSE, quote = FALSE)
}

bin_things <- function(df) {
  combined <- c()
  counter <- 0
  for (i in 0:max(df$distance)) {
    combined <- append(combined, i)
    counter <- counter + length(df$distance[df$distance==i])
    if(counter > 450) {
      if (length(combined) > 1) {
        add <- matrix(ncol = ncol(df))
        colnames(add) <- colnames(df)
        for (j in combined) {
          for (l in combined) {
            if (l == j) next
            mm <- df[df$distance == j, ]
            mm$distance <- l
            add <- rbind(add,mm)
          }
        }
        df <- rbind(df, na.omit(add))
      }
      combined <- c()
      counter <- 0
    }
  }
  #combine left over bins
  if (length(combined) > 1) {
    add <- matrix(ncol = ncol(df))
    colnames(add) <- colnames(df)
    for (j in combined) {
      for (l in combined) {
        if (l == j) next
        mm <- df[df$distance == j, ]
        mm$distance <- l
        add <- rbind(add,mm)
      }
    }
    df <- rbind(df, na.omit(add))
  }
  
  return(df)
}

#### MAIN ####

#the combined data points
data4tad <- read.delim(args[1], quote = "")
data4loop <- read.delim(args[2], quote = "")
data4back <- read.delim(args[3], quote = "")

#testing with data generated by taking all tads and loop/fl
data4tad <- read.delim(gzfile("/Users/ncolaian/Documents/phanstiel_lab/data/combined2_tad.txt.gz"), quote = "")
data4loop <- read.delim(gzfile("/Users/ncolaian/Documents/phanstiel_lab/data/combined2_lofl.txt.gz"), quote = "")
data4back <- read.delim(gzfile("/Users/ncolaian/Documents/phanstiel_lab/data/combined2_back.txt.gz"), quote = "")

#get output file path
outer <- args[4]
colnames(data4tad) <- c("distance", "reads", "used", "model")
colnames(data4loop) <- c("distance", "reads", "used", "model")
colnames(data4back) <- c("distance", "reads", "used", "model")

#Get the distance to the right spot
data4tad$distance <- as.character(data4tad$distance)
data4loop$distance <- as.character(data4loop$distance)
data4back$distance <- as.character(data4back$distance)

data4tad$distance <- gsub("^.*:", "", data4tad$distance)
data4loop$distance <- gsub("^.*:", "", data4loop$distance)
data4back$distance <- gsub("^.*:", "", data4back$distance)

data4tad$distance <- as.integer(data4tad$distance)
data4loop$distance <- as.integer(data4loop$distance)
data4back$distance <- as.integer(data4back$distance)

#test if data has enough counts for a bin
data4tad <- bin_things(data4tad)
data4loop <- bin_things(data4loop)
data4back <- bin_things(data4back)

#make dataframe
fit <- fit_distributions(data4tad, data4loop, data4back)

#print out table
print_out_data("distr_99", fit, outer)

#test out
outer <- "/Users/ncolaian/Documents/phanstiel_lab/data/"
print_out_data("distr_99", fit, outer)

#printing the gamma parameters
ggplot(fit, aes(x=distance, y=rate, col=model))+
  geom_line()



